### PR TITLE
Create mega-linter.yml

### PR DESCRIPTION
**Pull request by Lexzet21**
### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by AlaahT — APPROVED** [review]
Looks good!

**Comment by platisd** [comment]
I am planning to make the checks compulsory, so I suggest to ensure that the job passes ASAP. 👍

**Comment by AlaahT** [comment]
Is that ok to configurate our MegaLinter so that it ignores some irrelevant checks such as the copy-paste check and spelling check? Or do you want our Megalinter to pass all the default checks that it has?

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lexzet21** [comment]
Hello Dimitris! We are aware of the duplications in our ccs files and are
looking into that. As for stefanzweifel, we think it's some sort of signum
of a MegaLinter developer, which is not recognized by the spelling Linter
(check), so we are going to either 1) delete it from that file, if it seems
safe and doesn't affect the code, or 2) configure the spelling Linter to
recognize "stefanzweifel" as an existing word. I am currently looking into
MegaLinter configuration and we will reach back to you when this is done.
// Aleksey and group 15

Den tis 10 maj 2022 kl 19:48 skrev Dimitris Platis ***@***.***

**Comment by platisd** [comment]
The spelling mistake should be easy to ignore. There's usually some way (ie configuration file) to add "words". 👍

**Pull request merged**
