### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by AlaahT**
### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by anselin-thefirst — COMMENTED** [review]
use this link instead: https://www.youtube.com/watch?v=VPUr9Y1GWiA

**Review by anselin-thefirst — APPROVED** [review]
looks good

**Review by AlaahT — COMMENTED** [review]
Added the new link

**Comment by AlaahT** [comment]
Not valid anymore

**Pull request closed without merging**
