### PR TITLE
Web button

### PR DESCRIPTION
**Pull request by LabibaKararEshaba**
-Added functionality to the Admin page buttons so that the car directions can be controlled through website
-Created a new appearance for all the webpages, so that the website looks consistent  
-Decided to move predefined path webpage functionality to admin webpage
-Decided to remove predefined path webpage

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Dahlaan** [comment]
Looks great, good job on the css and html!

**Review by Dahlaan — APPROVED** [review]
Good job! Looks great!

**Review by Dahlaan — DISMISSED** [review]

**Review by Dahlaan — APPROVED** [review]

**Review by Dahlaan — APPROVED** [review]

**Review by anselin-thefirst — APPROVED** [review]
please?

**Review by JonnaJ98 — APPROVED** [review]
Looks good.

**Review by anselin-thefirst — APPROVED** [review]
yes

**Review by JonnaJ98 — DISMISSED** [review]

**Review by anselin-thefirst — APPROVED** [review]
yes

**Review by Dahlaan — APPROVED** [review]

**Review by Dahlaan — APPROVED** [review]
Well done!

**Pull request merged**
