### PR TITLE
Delete mega-linter.yml

### PR DESCRIPTION
**Pull request by Dahlaan**
This dosen't work, it hindering our progress, we can upload new workflows while this is in our repository. 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by JonnaJ98 — APPROVED** [review]

**Comment by platisd** [comment]
Deleting it means that you don't satisfy the grading criteria for the course. ⚠️
What do you propose instead?

**Comment by JonnaJ98** [comment]
@platisd 
We don't know what to do, this workflow is blocking us from even updating the readme file and then we can't submit today's assignment. Even if all the tests pass, which it has done for other pull requests it doesn't allow us to merge. It's stopping us from finishing the final version of our project.

**Comment by platisd** [comment]
First, today you are submitting the demo.
Secondly, even if today was the final submission, you'd fail the project without it.

You should either (a) configure it appropriately, (b) fix the errors, (c) replace it with an equivalent workflow that you have better understanding of.

**Comment by JonnaJ98** [comment]
@platisd 
Okay we understand, we are going to try to configure the megalinter. Is it okay if we submit the link to the branch where we have change the readme file? Because we won't be able to fix the megalinter today.

**Comment by platisd** [comment]
I wouldn't really say that it's "OK" since having a broken master branch without being able to merge is a very bad position to be in and action should have been already taken instead of waiting for the last moment.
But if there's no other way, submit a link to a branch, what can we do...

**Comment by platisd** [comment]
I noticed the issue that you have in the other pull request. Let's address it there. This pull request is not acceptable therefore I am closing it.

**Pull request closed without merging**
